
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xfb\x00\xee[\xa5\xdaY\x0bc\x05ZK,l\x17m'
    
_lr_action_items = {'OR':([2,4,43,50,55,63,70,73,75,76,78,84,],[-2,-1,-3,-3,60,-3,-3,-3,-3,-3,-3,-3,]),'NEG':([2,4,43,50,55,63,70,73,75,76,78,84,],[-2,-1,-3,-3,62,-3,-3,-3,-3,-3,-3,-3,]),'WEIGHT_START':([0,2,3,4,26,],[-3,-2,7,-1,-3,]),'RPAREN':([2,4,28,54,59,61,66,67,72,74,77,79,80,81,82,83,85,86,87,88,],[-2,-1,-23,-3,68,-30,-29,-28,-31,-3,80,-3,-32,-35,-3,86,88,-33,-36,-34,]),'LPAREN':([2,4,35,43,50,55,60,62,63,64,65,69,70,71,73,75,76,78,84,],[-2,-1,43,-3,-3,63,-38,-3,-3,-3,-37,73,-3,75,-3,-3,-3,-3,-3,]),'NEWLINE':([2,4,8,9,10,12,13,16,19,23,27,28,29,30,31,32,34,42,45,47,48,49,56,57,58,68,],[-2,-1,-8,-7,-3,-11,-9,-10,26,-17,-21,-23,-20,-13,-15,-12,-18,-26,-22,-15,-16,-19,-25,-24,-14,-27,]),'RANGE_OP':([2,23,31,39,40,],[-2,-17,-3,46,-1,]),'FORMULA_START':([0,2,3,4,26,],[-3,-2,6,-1,-3,]),'NODE_START':([0,2,3,4,26,],[-3,-2,14,-1,-3,]),'IDENTIFIER':([2,4,20,36,38,43,50,55,62,63,69,70,73,75,76,78,84,],[-2,-1,28,28,28,-3,-3,28,-3,-3,28,-3,-3,-3,-3,-3,-3,]),'AND':([2,4,43,50,55,63,70,73,75,76,78,84,],[-2,-1,-3,-3,65,-3,-3,-3,-3,-3,-3,-3,]),'$end':([1,5,26,37,],[-4,0,-5,-6,]),'INTEGER':([2,4,17,18,21,22,40,41,46,51,52,53,],[-2,-1,23,23,23,23,23,23,-3,56,23,23,]),'ALPHABET_START':([0,2,3,4,26,],[-3,-2,11,-1,-3,]),'EDGE_START':([0,2,3,4,26,],[-3,-2,15,-1,-3,]),'WHITESPACE':([0,2,4,6,7,8,9,10,11,12,13,14,15,16,23,24,25,26,27,28,29,30,31,32,33,34,42,43,44,45,46,47,48,49,50,54,56,57,58,60,61,62,63,64,65,66,67,68,70,72,73,74,75,76,78,79,80,81,82,84,86,87,88,],[4,-2,-1,17,18,-8,-7,4,20,-11,-9,21,22,-10,-17,35,36,4,38,-23,-20,-13,40,-12,41,-18,-26,4,51,-22,4,53,-16,-19,4,4,-25,-24,-14,-38,-30,4,4,4,-37,-29,-28,-27,4,-31,4,4,4,4,4,4,-32,84,4,4,-33,-36,-34,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FORM':([50,70,76,78,84,],[54,74,79,81,81,]),'NODE_RANGE':([21,],[30,]),'OPT_WHITESPACE':([0,10,26,31,43,46,50,54,62,63,64,70,73,74,75,76,78,79,82,84,],[3,19,3,39,50,52,55,59,69,70,71,55,76,77,78,55,55,83,85,55,]),'EDGE_LINE':([3,],[8,]),'NODE_LIST':([21,40,53,],[32,48,48,]),'WEIGHT':([51,],[57,]),'NODE_LINE':([3,],[9,]),'SIMPLE_FORM':([55,],[67,]),'FORMULA':([35,],[42,]),'LINE':([3,],[10,]),'FORMULA_LINE':([3,],[12,]),'COMPOUND_FORM':([55,],[66,]),'empty':([0,10,26,31,43,46,50,54,62,63,64,70,73,74,75,76,78,79,82,84,],[2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,]),'ALPHABET_LINE':([3,],[13,]),'ATOM':([20,36,38,55,69,],[27,44,27,61,72,]),'LINES':([0,26,],[1,37,]),'EDGE':([22,],[34,]),'OP':([55,],[64,]),'FORM_LIST':([78,84,],[82,87,]),'ATOM_LIST':([20,38,],[29,45,]),'FILE':([0,],[5,]),'NODE':([17,18,21,22,40,41,52,53,],[24,25,31,33,47,49,58,47,]),'WEIGHT_LINE':([3,],[16,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FILE","S'",1,None,None,None),
  ('OPT_WHITESPACE -> WHITESPACE','OPT_WHITESPACE',1,'p_OPT_WHITESPACE','BCF_Parser2.py',59),
  ('OPT_WHITESPACE -> empty','OPT_WHITESPACE',1,'p_OPT_WHITESPACE','BCF_Parser2.py',60),
  ('empty -> <empty>','empty',0,'p_empty','BCF_Parser2.py',64),
  ('FILE -> LINES','FILE',1,'p_FILE','BCF_Parser2.py',68),
  ('LINES -> OPT_WHITESPACE LINE OPT_WHITESPACE NEWLINE','LINES',4,'p_LINES','BCF_Parser2.py',73),
  ('LINES -> OPT_WHITESPACE LINE OPT_WHITESPACE NEWLINE LINES','LINES',5,'p_LINES','BCF_Parser2.py',74),
  ('LINE -> NODE_LINE','LINE',1,'p_LINE','BCF_Parser2.py',79),
  ('LINE -> EDGE_LINE','LINE',1,'p_LINE','BCF_Parser2.py',80),
  ('LINE -> ALPHABET_LINE','LINE',1,'p_LINE','BCF_Parser2.py',81),
  ('LINE -> WEIGHT_LINE','LINE',1,'p_LINE','BCF_Parser2.py',82),
  ('LINE -> FORMULA_LINE','LINE',1,'p_LINE','BCF_Parser2.py',83),
  ('NODE_LINE -> NODE_START WHITESPACE NODE_LIST','NODE_LINE',3,'p_NODE_LINE','BCF_Parser2.py',88),
  ('NODE_LINE -> NODE_START WHITESPACE NODE_RANGE','NODE_LINE',3,'p_NODE_LINE','BCF_Parser2.py',89),
  ('NODE_RANGE -> NODE OPT_WHITESPACE RANGE_OP OPT_WHITESPACE NODE','NODE_RANGE',5,'p_NODE_RANGE','BCF_Parser2.py',93),
  ('NODE_LIST -> NODE','NODE_LIST',1,'p_NODE_LIST','BCF_Parser2.py',99),
  ('NODE_LIST -> NODE WHITESPACE NODE_LIST','NODE_LIST',3,'p_NODE_LIST','BCF_Parser2.py',100),
  ('NODE -> INTEGER','NODE',1,'p_NODE','BCF_Parser2.py',104),
  ('EDGE_LINE -> EDGE_START WHITESPACE EDGE','EDGE_LINE',3,'p_EDGE_LINE','BCF_Parser2.py',110),
  ('EDGE -> NODE WHITESPACE NODE','EDGE',3,'p_EDGE','BCF_Parser2.py',115),
  ('ALPHABET_LINE -> ALPHABET_START WHITESPACE ATOM_LIST','ALPHABET_LINE',3,'p_ALPHABET_LINE','BCF_Parser2.py',120),
  ('ATOM_LIST -> ATOM','ATOM_LIST',1,'p_ATOM_LIST','BCF_Parser2.py',125),
  ('ATOM_LIST -> ATOM WHITESPACE ATOM_LIST','ATOM_LIST',3,'p_ATOM_LIST','BCF_Parser2.py',126),
  ('ATOM -> IDENTIFIER','ATOM',1,'p_ATOM','BCF_Parser2.py',131),
  ('WEIGHT_LINE -> WEIGHT_START WHITESPACE NODE WHITESPACE ATOM WHITESPACE WEIGHT','WEIGHT_LINE',7,'p_WEIGHT_LINE','BCF_Parser2.py',136),
  ('WEIGHT -> INTEGER','WEIGHT',1,'p_WEIGHT','BCF_Parser2.py',140),
  ('FORMULA_LINE -> FORMULA_START WHITESPACE NODE WHITESPACE FORMULA','FORMULA_LINE',5,'p_FORMULA_LINE','BCF_Parser2.py',144),
  ('FORMULA -> LPAREN OPT_WHITESPACE FORM OPT_WHITESPACE RPAREN','FORMULA',5,'p_FORMULA','BCF_Parser2.py',149),
  ('FORM -> OPT_WHITESPACE SIMPLE_FORM','FORM',2,'p_FORM','BCF_Parser2.py',154),
  ('FORM -> OPT_WHITESPACE COMPOUND_FORM','FORM',2,'p_FORM','BCF_Parser2.py',155),
  ('SIMPLE_FORM -> ATOM','SIMPLE_FORM',1,'p_SIMPLE_FORM','BCF_Parser2.py',160),
  ('SIMPLE_FORM -> NEG OPT_WHITESPACE ATOM','SIMPLE_FORM',3,'p_SIMPLE_FORM','BCF_Parser2.py',161),
  ('SIMPLE_FORM -> LPAREN OPT_WHITESPACE FORM OPT_WHITESPACE RPAREN','SIMPLE_FORM',5,'p_SIMPLE_FORM','BCF_Parser2.py',162),
  ('SIMPLE_FORM -> NEG OPT_WHITESPACE LPAREN OPT_WHITESPACE FORM OPT_WHITESPACE RPAREN','SIMPLE_FORM',7,'p_SIMPLE_FORM','BCF_Parser2.py',163),
  ('COMPOUND_FORM -> OP OPT_WHITESPACE LPAREN OPT_WHITESPACE FORM_LIST OPT_WHITESPACE RPAREN','COMPOUND_FORM',7,'p_COMPOUND_FORM','BCF_Parser2.py',175),
  ('FORM_LIST -> FORM','FORM_LIST',1,'p_FORM_LIST','BCF_Parser2.py',180),
  ('FORM_LIST -> FORM WHITESPACE FORM_LIST','FORM_LIST',3,'p_FORM_LIST','BCF_Parser2.py',181),
  ('OP -> AND','OP',1,'p_OP','BCF_Parser2.py',186),
  ('OP -> OR','OP',1,'p_OP','BCF_Parser2.py',187),
]
