
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'~\xb3f\x93v\xfb?\xf8\x1c\x1a\x86\xb2\xf2\xb6\x92i'
    
_lr_action_items = {'NEG':([3,4,6,8,14,22,26,29,30,32,39,],[-18,-17,-19,11,-19,11,-19,-19,11,11,11,]),'$end':([2,3,4,5,7,28,],[0,-18,-17,-19,-1,-2,]),'IDENTIFIER':([3,4,6,8,11,14,21,22,26,29,30,32,39,],[-18,-17,-19,10,-19,-19,10,10,-19,-19,10,10,10,]),'OR':([3,4,6,8,14,22,26,29,30,32,39,],[-18,-17,-19,20,-19,20,-19,-19,20,20,20,]),'RPAREN':([3,4,10,12,13,15,17,23,25,27,31,33,34,35,36,37,38,39,40,41,42,43,],[-18,-17,-12,-5,-4,-3,-19,28,-6,-19,34,-19,-7,-19,-19,41,-10,-17,43,-8,-11,-9,]),'LPAREN':([0,1,3,4,6,8,9,11,14,16,18,19,20,21,22,24,26,29,30,32,39,],[-19,6,-18,-17,-19,14,-14,-19,-19,-15,-13,-19,-16,26,14,29,-19,-19,14,14,14,]),'AND':([3,4,6,8,14,22,26,29,30,32,39,],[-18,-17,-19,16,-19,16,-19,-19,16,16,16,]),'WHITESPACE':([0,3,5,6,9,10,11,12,13,14,15,16,17,18,19,20,25,26,27,28,29,33,34,35,36,38,39,41,42,43,],[4,-18,4,4,-14,-12,4,-5,-4,4,-3,-15,4,-13,4,-16,-6,4,4,-2,4,4,-7,39,4,-10,-17,-8,-11,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'OR_OP':([8,22,30,32,39,],[9,9,9,9,9,]),'FORMULA_LINE':([0,],[2,]),'ATOM':([8,21,22,30,32,39,],[12,25,12,12,12,12,]),'COMPOUND_FORM':([8,22,30,32,39,],[13,13,13,13,13,]),'empty':([0,5,6,11,14,17,19,26,27,29,33,35,36,],[3,3,3,3,3,3,3,3,3,3,3,3,3,]),'SIMPLE_FORM':([8,22,30,32,39,],[15,15,15,15,15,]),'OPT_WHITESPACE':([0,5,6,11,14,17,19,26,27,29,33,35,36,],[1,7,8,21,22,23,24,30,31,32,37,38,40,]),'FORMULA':([1,],[5,]),'FORM':([8,22,30,32,39,],[17,27,33,35,35,]),'AND_OP':([8,22,30,32,39,],[18,18,18,18,18,]),'OP':([8,22,30,32,39,],[19,19,19,19,19,]),'FORM_LIST':([32,39,],[36,42,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FORMULA_LINE","S'",1,None,None,None),
  ('FORMULA_LINE -> OPT_WHITESPACE FORMULA OPT_WHITESPACE','FORMULA_LINE',3,'p_FORMULA_LINE','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',36),
  ('FORMULA -> LPAREN OPT_WHITESPACE FORM OPT_WHITESPACE RPAREN','FORMULA',5,'p_FORMULA','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',40),
  ('FORM -> SIMPLE_FORM','FORM',1,'p_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',45),
  ('FORM -> COMPOUND_FORM','FORM',1,'p_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',46),
  ('SIMPLE_FORM -> ATOM','SIMPLE_FORM',1,'p_SIMPLE_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',51),
  ('SIMPLE_FORM -> NEG OPT_WHITESPACE ATOM','SIMPLE_FORM',3,'p_SIMPLE_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',52),
  ('SIMPLE_FORM -> LPAREN OPT_WHITESPACE FORM OPT_WHITESPACE RPAREN','SIMPLE_FORM',5,'p_SIMPLE_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',53),
  ('SIMPLE_FORM -> NEG OPT_WHITESPACE LPAREN OPT_WHITESPACE FORM OPT_WHITESPACE RPAREN','SIMPLE_FORM',7,'p_SIMPLE_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',54),
  ('COMPOUND_FORM -> OP OPT_WHITESPACE LPAREN OPT_WHITESPACE FORM_LIST OPT_WHITESPACE RPAREN','COMPOUND_FORM',7,'p_COMPOUND_FORM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',66),
  ('FORM_LIST -> FORM OPT_WHITESPACE','FORM_LIST',2,'p_FORM_LIST','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',70),
  ('FORM_LIST -> FORM WHITESPACE FORM_LIST','FORM_LIST',3,'p_FORM_LIST','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',71),
  ('ATOM -> IDENTIFIER','ATOM',1,'p_ATOM','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',76),
  ('OP -> AND_OP','OP',1,'p_OP','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',81),
  ('OP -> OR_OP','OP',1,'p_OP','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',82),
  ('AND_OP -> AND','AND_OP',1,'p_AND_OP','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',90),
  ('OR_OP -> OR','OR_OP',1,'p_OR_OP','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',97),
  ('OPT_WHITESPACE -> WHITESPACE','OPT_WHITESPACE',1,'p_OPT_WHITESPACE','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',101),
  ('OPT_WHITESPACE -> empty','OPT_WHITESPACE',1,'p_OPT_WHITESPACE','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',102),
  ('empty -> <empty>','empty',0,'p_empty','/Users/paulvicol/Learn/Python/ParserTests/SimpleWorking/FormulaParserSim.py',106),
]
